//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GivingBack2.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiveBackDBEntities : DbContext
    {
        public GiveBackDBEntities()
            : base("name=GiveBackDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HelpCategory> HelpCategories { get; set; }
        public virtual DbSet<MoneyResource> MoneyResources { get; set; }
        public virtual DbSet<OrgDetail> OrgDetails { get; set; }
        public virtual DbSet<ProductResource> ProductResources { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<TimeResource> TimeResources { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
