//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GivingBack2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirement()
        {
            this.MoneyResources = new HashSet<MoneyResource>();
            this.ProductResources = new HashSet<ProductResource>();
            this.TimeResources = new HashSet<TimeResource>();
        }
    
        public long ReqId { get; set; }
        public Nullable<long> OrgId { get; set; }
        public Nullable<long> ResourceId { get; set; }
        public Nullable<long> ReceiverId { get; set; }
        public string Description { get; set; }
    
        public virtual HelpCategory HelpCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyResource> MoneyResources { get; set; }
        public virtual OrgDetail OrgDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductResource> ProductResources { get; set; }
        public virtual Resource Resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeResource> TimeResources { get; set; }
    }
}
